USE Kcal
GO
DROP TABLE Jidelnicek,OsobniJidlo,Jidlo,Status,Uzivatel,Funkce
GO
CREATE TABLE Funkce
(
IDFunkce INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
Nazev VARCHAR(20) NOT NULL,
Popis VARCHAR(100) NULL
)
GO
CREATE TABLE Uzivatel
(
IDUzivatel INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
IDFunkce INT NOT NULL FOREIGN KEY REFERENCES Funkce(IDFunkce), 
Jmeno VARCHAR(20) NOT NULL,
Prijmeni VARCHAR(20) NOT NULL,
Email VARCHAR(50) NOT NULL UNIQUE CHECK (Email LIKE('%_@_%.__%')),
Heslo VARCHAR(20) NOT NULL CHECK (Heslo LIKE ('%[0-9]%' ) AND LEN(Heslo) > 7),
Telefon VARCHAR(15) NULL,
DatumNarozeni DATE NOT NULL,
Potvrzen BIT NOT NULL DEFAULT 0,
PosledniLog DATETIME NOT NULL DEFAULT GETDATE()
)
GO
CREATE TABLE Status
(
IDStatus INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
IDUzivatel INT NOT NULL FOREIGN KEY REFERENCES Uzivatel(IDUzivatel),
Vaha DECIMAL(5,2) NOT NULL,
Datum DATETIME NOT NULL DEFAULT GETDATE(),
Poznamka VARCHAR(100) NULL
)
GO
CREATE TABLE Jidlo
(
IDJidlo INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
Nazev VARCHAR(50) NOT NULL,
Popis VARCHAR(100) NULL,
VahaGramy DECIMAL(5,2) NOT NULL, --váha jídla v gramech
Bilkoviny DECIMAL(5,2) NULL, --nutrièní hodnoty na 100géèek
Tuky DECIMAL(5,2) NULL,
Sacharidy DECIMAL(5,2) NULL,
Cukry DECIMAL(5,2) NULL,
Kcal DECIMAL(5,2) NOT NULL
)
CREATE TABLE OsobniJidlo
(
IDOsobniJidlo INT IDENTITY(1,1) NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES Jidlo(IDJidlo),
--IDJidlo INT NOT NULL FOREIGN KEY REFERENCES Jidlo(IDJidlo),
VlastniNazev VARCHAR(50) NOT NULL,
VlastniPopis VARCHAR(100) NULL,
)
GO
CREATE TABLE Jidelnicek
(
IDJidelnicek INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
IDUzivatel INT NOT NULL FOREIGN KEY REFERENCES Uzivatel(IDUzivatel),
IDJidlo INT NOT NULL FOREIGN KEY REFERENCES Jidlo(IDJidlo),
Typ VARCHAR(20) NOT NULL, --obìd, snídanì, svaèina atd
Cas DATETIME NOT NULL DEFAULT GETDATE(),
Poznamka VARCHAR(50) NULL
)